### ISSUE TITLE
make show layers expansion panel

### ISSUE THREAD

**Issue by CindyvdVries** [openearth/deltares-global-data-services#8]
Make a panel with a list of available layers

- [ ] icon with example of layers
- [x] name of the layer
- [x] checkbox
- [ ] timeslider (disabled)
- [x] When the checkbox in the show layer panel is checked, show the specific datalayers

**Comment by DELTAmats** [comment]
moeten die laatste twee ook nog?

**Comment by DELTAmats** [comment]
made 2 new issues for the final 2
